name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  RUST_BACKTRACE: 1

jobs:
  build_and_test:
    name: valibuk - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fail-fast: false
        toolchain:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: make build
      - run: make test
  
